"""add transactionmeta

Revision ID: aa5fe6c1b78d
Revises: d9bb0c6cbea0
Create Date: 2018-06-08 11:44:02.071954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa5fe6c1b78d'
down_revision = 'd9bb0c6cbea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_meta',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.Unicode(length=255), nullable=False),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id', 'key'),
    schema='history_sqlalchemy'
    )
    op.drop_column('transaction', 'user_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('user_info', mysql.TEXT(), nullable=True))
    op.drop_table('transaction_meta', schema='history_sqlalchemy')
    # ### end Alembic commands ###
